/*
 * Copyright (c) 2026 Kory Heard
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

import Foundation

// MARK: - ProfileLoader

/// Loads `.d` profile files from the three standard locations and
/// resolves name collisions via shadowing rules.
///
/// Sources, in increasing precedence:
///   1. Bundled SwiftPM resources inside the dtlm binary
///   2. `/usr/local/share/dtlm/profiles/`
///   3. `~/.dtlm/profiles/`
///
/// Each source is scanned at startup; if a profile name appears in
/// multiple sources the highest-priority one wins, with a warning
/// emitted to stderr listing both paths so the user knows what got
/// shadowed.
struct ProfileLoader: Sendable {

    /// Construct a loader and scan all three sources eagerly.
    init() {
        var byName: [String: Profile] = [:]
        var shadowedWarnings: [String] = []

        // Source 1: bundled SwiftPM resources.
        for profile in Self.loadBundled() {
            byName[profile.name] = profile
        }

        // Source 2: system dir.
        for profile in Self.loadDirectory(
            atPath: "/usr/local/share/dtlm/profiles",
            origin: .systemDir
        ) {
            if let existing = byName[profile.name],
               existing.origin < profile.origin
            {
                shadowedWarnings.append(
                    "dtlm: profile '\(profile.name)' from \(profile.origin.displayName) "
                    + "shadows \(existing.origin.displayName) version"
                )
            }
            byName[profile.name] = profile
        }

        // Source 3: user dir.
        if let home = ProcessInfo.processInfo.environment["HOME"] {
            let userPath = "\(home)/.dtlm/profiles"
            for profile in Self.loadDirectory(atPath: userPath, origin: .userDir) {
                if let existing = byName[profile.name],
                   existing.origin < profile.origin
                {
                    shadowedWarnings.append(
                        "dtlm: profile '\(profile.name)' from \(profile.origin.displayName) "
                        + "shadows \(existing.origin.displayName) version"
                    )
                }
                byName[profile.name] = profile
            }
        }

        self.profiles = byName
        self.shadowingWarnings = shadowedWarnings
    }

    /// Every profile keyed by name (after shadowing has resolved).
    let profiles: [String: Profile]

    /// Diagnostics emitted at construction time. Callers should
    /// print these to stderr at startup.
    let shadowingWarnings: [String]

    /// Look up a profile by name.
    func lookup(_ name: String) -> Profile? {
        profiles[name]
    }

    /// Every profile, sorted by name for stable display.
    func all() -> [Profile] {
        profiles.values.sorted { $0.name < $1.name }
    }

    /// Number of loaded profiles.
    var count: Int { profiles.count }

    // MARK: - Loading from a filesystem directory

    private static func loadDirectory(
        atPath path: String,
        origin: ProfileOrigin
    ) -> [Profile] {
        let fm = FileManager.default
        var isDir: ObjCBool = false
        guard fm.fileExists(atPath: path, isDirectory: &isDir), isDir.boolValue else {
            // Missing directory is fine — most installs won't have
            // every source dir present.
            return []
        }

        guard let entries = try? fm.contentsOfDirectory(atPath: path) else {
            return []
        }

        var loaded: [Profile] = []
        for entry in entries where entry.hasSuffix(".d") {
            let fullPath = (path as NSString).appendingPathComponent(entry)
            do {
                let source = try String(contentsOfFile: fullPath, encoding: .utf8)
                let name = String(entry.dropLast(2))   // strip .d
                loaded.append(Profile(
                    name: name,
                    description: parseDescription(from: source),
                    source: source,
                    origin: origin
                ))
            } catch {
                FileHandle.standardError.write(Data(
                    "dtlm: failed to read \(fullPath): \(error)\n".utf8
                ))
            }
        }
        return loaded
    }

    // MARK: - Loading from SwiftPM bundled resources

    private static func loadBundled() -> [Profile] {
        // Bundle.module is generated by SwiftPM when the target
        // declares resources. It points at the directory holding the
        // bundled .d files.
        let bundle = Bundle.module
        guard let resourceURL = bundle.resourceURL else {
            return []
        }

        // The .process("Profiles") declaration in Package.swift
        // copies Profiles/*.d into the bundle root, so we look at
        // the bundle's resourceURL for *.d files.
        let fm = FileManager.default
        guard let entries = try? fm.contentsOfDirectory(
            at: resourceURL,
            includingPropertiesForKeys: nil
        ) else {
            return []
        }

        var loaded: [Profile] = []
        for url in entries where url.pathExtension == "d" {
            do {
                let source = try String(contentsOf: url, encoding: .utf8)
                let name = url.deletingPathExtension().lastPathComponent
                loaded.append(Profile(
                    name: name,
                    description: parseDescription(from: source),
                    source: source,
                    origin: .bundled
                ))
            } catch {
                FileHandle.standardError.write(Data(
                    "dtlm: failed to read bundled \(url.lastPathComponent): \(error)\n".utf8
                ))
            }
        }
        return loaded
    }

    /// Parse the first `/* ... */` block comment from a `.d` file
    /// and return a single-line description. For multi-line block
    /// comments dtlm strips the leading `*` decoration on each line
    /// and returns the first non-empty line — that becomes the
    /// short description shown in `dtlm list`.
    ///
    /// Returns the empty string if there's no leading block comment.
    static func parseDescription(from source: String) -> String {
        // Find the first `/*` and the matching `*/`.
        guard let openRange = source.range(of: "/*"),
              let closeRange = source.range(of: "*/", range: openRange.upperBound..<source.endIndex)
        else {
            return ""
        }
        let inner = source[openRange.upperBound..<closeRange.lowerBound]

        // Walk lines, strip leading whitespace and `*` decoration,
        // and pick the first non-empty result.
        for rawLine in inner.split(whereSeparator: { $0.isNewline }) {
            var line = rawLine.trimmingCharacters(in: .whitespaces)
            // Strip a single leading `*` (the doc-comment line decoration).
            if line.hasPrefix("*") {
                line = String(line.dropFirst()).trimmingCharacters(in: .whitespaces)
            }
            if !line.isEmpty {
                return line
            }
        }
        return ""
    }
}

// MARK: - Loading a single explicit file

extension ProfileLoader {
    /// Load a single `.d` file from an explicit path. Used by
    /// `dtlm watch -f /path/to/script.d`.
    static func loadExplicit(path: String) throws -> Profile {
        let source: String
        do {
            source = try String(contentsOfFile: path, encoding: .utf8)
        } catch {
            throw ProfileError.readFailed(path: path, underlying: error)
        }

        // Use the basename (sans .d) as the synthetic profile name.
        let url = URL(fileURLWithPath: path)
        let name = url.deletingPathExtension().lastPathComponent

        return Profile(
            name: name,
            description: parseDescription(from: source),
            source: source,
            origin: .explicit
        )
    }
}
